### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by Juanlu001** [satellogic/orbit-predictor#12]
It would be great to have #8 in a pip-installable release. Perhaps 1.9.0? Or you prefer 1.8.7?

**Comment by Juanlu001** [comment]
* [ ] Address @spiccinini comments about deprecation warnings
* [ ] Remove support for tz-aware objects, which was never relased in a stable version anyway
* [ ] #32 
* [ ] #40 
* [ ] #41
* [ ] Release notes
* [ ] Tag, PyPI

**Comment by spiccinini** [comment]
1.9 sounds good!
