### ISSUE TITLE
master is not built in Travis CI

### ISSUE THREAD

**Issue by Juanlu001** [satellogic/orbit-predictor#5]
So there is no build status (grey badge on README) and no base report for Coveralls (see https://github.com/satellogic/orbit-predictor/pull/4#issuecomment-344286860).

**Comment by gilgamezh** [comment]
![image](https://user-images.githubusercontent.com/1496486/32794704-50629ee0-c948-11e7-8ee6-1bae477f9143.png)

I updated travis-ci to "build branch updates"

**Comment by Juanlu001** [comment]
It's working now. Closing!
