### ISSUE TITLE
Evaluate new Satrec API from sgp4

### ISSUE THREAD

**Issue by astrojuanlu** [satellogic/orbit-predictor#82]
There is a [new API in sgp4](https://pypi.org/project/sgp4/#description):

```
>>> from sgp4.api import Satrec
>>>
>>> s = '1 25544U 98067A   19343.69339541  .00001764  00000-0  38792-4 0  9991'
>>> t = '2 25544  51.6439 211.2001 0007417  17.6667  85.6398 15.50103472202482'
>>> satellite = Satrec.twoline2rv(s, t)
>>>
>>> jd, fr = 2458827, 0.362605
>>> e, r, v = satellite.sgp4(jd, fr)
>>> e
0
>>> print(r)
(-6102.44..., -986.33..., -2820.31...)
>>> print(v)
(-1.45..., -5.52..., 5.10...)
```

However, it requires some changes:

* For the moment, [WGS-72 is hardcoded](https://github.com/brandon-rhodes/python-sgp4/issues/47)
* The equivalent of the `propagate` method is `Satrec.sgp4` (and `Satrec.sgp4_array`), which now receive "the whole part and the fractional part" of the Julian date, therefore some conversion is needed [and it's not clear how to do it](https://github.com/satellogic/orbit-predictor/issues/83)

**Comment by Juanlu001** [comment]
In progress in #86.

**Comment by astrojuanlu** [comment]
This was merged and released!
