### ISSUE TITLE
Test failing in master

### ISSUE THREAD

**Issue by astrojuanlu** [satellogic/orbit-predictor#89]
...and we didn't notice.

**Good** :heavy_check_mark: 2019-12-27 https://travis-ci.org/satellogic/orbit-predictor/jobs/629930607
**Bad** :red_circle: 2020-01-04 https://travis-ci.org/satellogic/orbit-predictor/jobs/632500551

Same commit, a few days apart. Can't reproduce locally. Spot the difference...

**Comment by Juanlu001** [comment]
Well, it seems that the test is failing quite randomly. Let's just edit it.

**Comment by Juanlu001** [comment]
Confirmed: restarted the job at https://github.com/satellogic/orbit-predictor/pull/87, and the test passed.

**Comment by Juanlu001** [comment]
For reference, it's `test_sun_sync_delta_true_anomaly_has_expected_anomaly_and_epoch`.
